// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0nOHC0GAbv0jDAG7DUv25CShMAv-jKuo',
    appId: '1:1112686659:web:ccd4a5712456d8f24fd4f6',
    messagingSenderId: '1112686659',
    projectId: 'notes-975',
    authDomain: 'notes-975.firebaseapp.com',
    storageBucket: 'notes-975.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgkkKtmMW4ZtW7c1IVd6LDDWnbpQko48A',
    appId: '1:1112686659:android:fe82e206712d79bf4fd4f6',
    messagingSenderId: '1112686659',
    projectId: 'notes-975',
    storageBucket: 'notes-975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKauZy1gWGx_ttJiXBY6WhXFrbzXQAYo',
    appId: '1:1112686659:ios:bdf5727feae018a74fd4f6',
    messagingSenderId: '1112686659',
    projectId: 'notes-975',
    storageBucket: 'notes-975.appspot.com',
    iosClientId: '1112686659-olg2mvuiqjo5o2gb7hmroc8uobk2ir66.apps.googleusercontent.com',
    iosBundleId: 'com.jtr03.mynotes',
  );
}
